<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.psi</groupId>
        <artifactId>psi-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>psi-message</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- Spring Boot Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        
        <!-- Common Core -->
        <dependency>
            <groupId>com.psi</groupId>
            <artifactId>psi-common-core</artifactId>
        </dependency>
        
        <!-- Nacos -->
        <dependency>
            <groupId>com.psi</groupId>
            <artifactId>psi-common-starter-nacos</artifactId>
        </dependency>
        
        <!-- MyBatis Plus -->
        <dependency>
            <groupId>com.psi</groupId>
            <artifactId>psi-common-starter-mybatis</artifactId>
        </dependency>
        
        <!-- Tenant -->
        <dependency>
            <groupId>com.psi</groupId>
            <artifactId>psi-common-starter-tenant</artifactId>
        </dependency>
        
        <!-- Log -->
        <dependency>
            <groupId>com.psi</groupId>
            <artifactId>psi-common-starter-log</artifactId>
        </dependency>
        
        <!-- Trace -->
        <dependency>
            <groupId>com.psi</groupId>
            <artifactId>psi-common-starter-trace</artifactId>
        </dependency>
        
        <!-- Async -->
        <dependency>
            <groupId>com.psi</groupId>
            <artifactId>psi-common-starter-async</artifactId>
        </dependency>
        
        <!-- MQ Starter -->
        <dependency>
            <groupId>com.psi</groupId>
            <artifactId>psi-common-starter-mq</artifactId>
        </dependency>
        
        <!-- MySQL 数据库驱动 -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                    <skip>false</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>