CREATE TABLE IF NOT EXISTS `goods` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `goods_code` VARCHAR(64) NOT NULL COMMENT '商品编码',
    `goods_name` VARCHAR(128) NOT NULL COMMENT '商品名称',
    `goods_name_en` VARCHAR(256) DEFAULT NULL COMMENT '商品英文名称',
    `category_id` BIGINT DEFAULT NULL COMMENT '分类ID',
    `brand_id` BIGINT DEFAULT NULL COMMENT '品牌ID',
    `goods_spec` VARCHAR(256) DEFAULT NULL COMMENT '商品规格',
    `unit` VARCHAR(32) DEFAULT NULL COMMENT '计量单位',
    `image_url` VARCHAR(512) DEFAULT NULL COMMENT '主图URL',
    `images` TEXT DEFAULT NULL COMMENT '图片列表（JSON数组）',
    `description` TEXT DEFAULT NULL COMMENT '商品描述',
    `features` TEXT DEFAULT NULL COMMENT '商品特性（JSON数组）',
    `stock_qty` INT DEFAULT NULL COMMENT '库存数量',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '供应商编码',
    `weight` INT DEFAULT NULL COMMENT '重量',
    `weight_unit` VARCHAR(32) DEFAULT NULL COMMENT '重量单位',
    `package_spec` VARCHAR(256) DEFAULT NULL COMMENT '包装规格',
    `certification` VARCHAR(512) DEFAULT NULL COMMENT '认证信息',
    `view_count` INT DEFAULT 0 COMMENT '浏览量',
    `sort_order` INT DEFAULT 0 COMMENT '排序序号',
    `status` TINYINT DEFAULT 0 COMMENT '状态(0:启用 1:禁用)',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_goods_code` (`goods_code`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    INDEX `idx_category_id` (`category_id`),
    INDEX `idx_brand_id` (`brand_id`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品主表';

CREATE TABLE IF NOT EXISTS `goods_category` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `category_name` VARCHAR(128) NOT NULL COMMENT '分类名称',
    `category_code` VARCHAR(64) NOT NULL COMMENT '分类编码',
    `parent_id` BIGINT DEFAULT NULL COMMENT '父分类ID',
    `level` INT DEFAULT 1 COMMENT '分类层级',
    `sort_order` INT DEFAULT 0 COMMENT '排序序号',
    `icon` VARCHAR(512) DEFAULT NULL COMMENT '分类图标',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '分类描述',
    `status` TINYINT DEFAULT 0 COMMENT '状态(0:启用 1:禁用)',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_category_code` (`category_code`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    INDEX `idx_parent_id` (`parent_id`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品分类表';

CREATE TABLE IF NOT EXISTS `goods_brand` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `brand_name` VARCHAR(128) NOT NULL COMMENT '品牌名称',
    `brand_code` VARCHAR(64) NOT NULL COMMENT '品牌编码',
    `brand_logo` VARCHAR(512) DEFAULT NULL COMMENT '品牌Logo',
    `brand_desc` VARCHAR(500) DEFAULT NULL COMMENT '品牌描述',
    `website` VARCHAR(256) DEFAULT NULL COMMENT '品牌官网',
    `sort_order` INT DEFAULT 0 COMMENT '排序序号',
    `status` TINYINT DEFAULT 0 COMMENT '状态(0:启用 1:禁用)',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_brand_code` (`brand_code`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品品牌表';

CREATE TABLE IF NOT EXISTS `goods_unit` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `unit_code` VARCHAR(64) NOT NULL COMMENT '单位编码',
    `unit_name` VARCHAR(128) NOT NULL COMMENT '单位名称',
    `unit_symbol` VARCHAR(32) DEFAULT NULL COMMENT '单位符号（如：kg、m、件）',
    `unit_type` VARCHAR(32) DEFAULT NULL COMMENT '单位类型（WEIGHT-重量单位，VOLUME-体积单位，COUNT-计数单位，OTHER-其他）',
    `conversion_rate` DECIMAL(18,4) DEFAULT NULL COMMENT '换算比例（相对于基础单位的换算系数）',
    `base_unit_id` BIGINT DEFAULT NULL COMMENT '基础单位ID（父单位ID）',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '描述',
    `sort_order` INT DEFAULT 0 COMMENT '排序序号',
    `status` TINYINT DEFAULT 0 COMMENT '状态(0:启用 1:禁用)',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_unit_code` (`unit_code`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    INDEX `idx_base_unit_id` (`base_unit_id`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品单位表';

CREATE TABLE IF NOT EXISTS `goods_sku` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `goods_id` BIGINT NOT NULL COMMENT '商品ID',
    `sku_code` VARCHAR(64) NOT NULL COMMENT 'SKU编码',
    `spec_values` VARCHAR(512) DEFAULT NULL COMMENT '规格值（逗号分隔）',
    `spec_json` TEXT DEFAULT NULL COMMENT '规格JSON',
    `cost_price` DECIMAL(18,4) DEFAULT NULL COMMENT '成本价',
    `sale_price` DECIMAL(18,4) DEFAULT NULL COMMENT '销售价',
    `market_price` DECIMAL(18,4) DEFAULT NULL COMMENT '市场价',
    `barcode` VARCHAR(64) DEFAULT NULL COMMENT '条形码',
    `image_url` VARCHAR(512) DEFAULT NULL COMMENT '图片URL',
    `stock_qty` INT DEFAULT NULL COMMENT '库存数量',
    `min_stock_qty` INT DEFAULT NULL COMMENT '最低库存',
    `max_stock_qty` INT DEFAULT NULL COMMENT '最高库存',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '供应商编码',
    `weight` DECIMAL(18,4) DEFAULT NULL COMMENT '重量',
    `weight_unit` VARCHAR(32) DEFAULT NULL COMMENT '重量单位',
    `volume` DECIMAL(18,4) DEFAULT NULL COMMENT '体积',
    `volume_unit` VARCHAR(32) DEFAULT NULL COMMENT '体积单位',
    `package_spec` VARCHAR(256) DEFAULT NULL COMMENT '包装规格',
    `sales_count` INT DEFAULT 0 COMMENT '销量',
    `base_unit` VARCHAR(32) DEFAULT NULL COMMENT '基础单位（如：kg、g、件）',
    `sale_unit` VARCHAR(32) DEFAULT NULL COMMENT '销售单位（如：包、箱、盒）',
    `unit_conversion` VARCHAR(64) DEFAULT NULL COMMENT '单位换算（如：0.4kg/包）',
    `goods_unify_code` VARCHAR(64) DEFAULT NULL COMMENT '商品统一编码（同品多批次共用同一个编码）',
    `tax_rate` DECIMAL(5,4) DEFAULT 0.1600 COMMENT 'VAT税率（如0.1600表示16%）',
    `is_tax_inclusive` TINYINT DEFAULT 0 COMMENT '标价是否含税(0:否 1:是)',
    `sale_price_usd` DECIMAL(12,4) DEFAULT 0.0000 COMMENT 'USD销售价',
    `cost_price_usd` DECIMAL(12,4) DEFAULT 0.0000 COMMENT 'USD成本价',
    `sort_order` INT DEFAULT 0 COMMENT '排序序号',
    `status` TINYINT DEFAULT 0 COMMENT '状态(0:启用 1:禁用)',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_sku_code` (`sku_code`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    INDEX `idx_goods_id` (`goods_id`),
    INDEX `idx_barcode` (`barcode`),
    INDEX `idx_goods_unify_code` (`goods_unify_code`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SKU表';

CREATE TABLE IF NOT EXISTS `goods_sku_sale_unit` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `sku_id` BIGINT NOT NULL COMMENT 'SKU ID',
    `goods_unify_code` VARCHAR(64) DEFAULT NULL COMMENT '商品统一编码（同品多批次共用同一个编码）',
    `barcode` VARCHAR(64) DEFAULT NULL COMMENT '条码',
    `goods_name` VARCHAR(128) DEFAULT NULL COMMENT '商品名称',
    `category_id` BIGINT DEFAULT NULL COMMENT '商品分类ID',
    `brand_id` BIGINT DEFAULT NULL COMMENT '商品品牌ID',
    `image_url` VARCHAR(512) DEFAULT NULL COMMENT '商品图片URL',
    `sale_unit_id` BIGINT DEFAULT NULL COMMENT '销售单位ID',
    `sale_unit_name` VARCHAR(128) DEFAULT NULL COMMENT '销售单位名称',
    `sale_unit_symbol` VARCHAR(32) DEFAULT NULL COMMENT '销售单位符号',
    `conversion_rate` DECIMAL(18,4) DEFAULT NULL COMMENT '换算比例（相对于SKU基础单位）',
    `package_spec` VARCHAR(256) DEFAULT NULL COMMENT '包装规格描述',
    `sale_price` DECIMAL(18,4) DEFAULT NULL COMMENT '销售价格',
    `cost_price` DECIMAL(18,4) DEFAULT NULL COMMENT '成本价格',
    `tax_rate` DECIMAL(5,4) DEFAULT 0.1600 COMMENT 'VAT税率（如0.1600表示16%）',
    `is_tax_inclusive` TINYINT DEFAULT 0 COMMENT '标价是否含税(0:否 1:是)',
    `sale_price_usd` DECIMAL(12,4) DEFAULT 0.0000 COMMENT 'USD销售价',
    `batch_managed` TINYINT DEFAULT 0 COMMENT '是否管理批次/效期(0:否 1:是)',
    `stock_qty` DECIMAL(18,4) DEFAULT NULL COMMENT '库存数量',
    `min_stock_qty` DECIMAL(18,4) DEFAULT NULL COMMENT '最低库存',
    `is_default` TINYINT DEFAULT 0 COMMENT '是否默认销售单位(0:否 1:是)',
    `status` TINYINT DEFAULT 0 COMMENT '是否启用(0:禁用 1:启用)',
    `sort_order` INT DEFAULT 0 COMMENT '排序序号',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    INDEX `idx_sku_id` (`sku_id`),
    INDEX `idx_barcode` (`barcode`),
    INDEX `idx_goods_unify_code` (`goods_unify_code`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SKU销售单位表';

CREATE TABLE IF NOT EXISTS `goods_adjust_price_main` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `adjust_no` VARCHAR(64) NOT NULL COMMENT '调价单号',
    `doc_name` VARCHAR(128) DEFAULT NULL COMMENT '单据名称',
    `shop_code` VARCHAR(64) DEFAULT NULL COMMENT '商铺编码',
    `shop_name` VARCHAR(128) DEFAULT NULL COMMENT '商铺名称',
    `adjust_date` VARCHAR(32) DEFAULT NULL COMMENT '调价日期',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '总金额',
    `item_count` INT DEFAULT 0 COMMENT '明细项数',
    `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `status` TINYINT DEFAULT 0 COMMENT '状态(0:草稿 1:已提交 2:已审核)',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_adjust_no` (`adjust_no`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    INDEX `idx_status` (`status`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品调价单主表';

CREATE TABLE IF NOT EXISTS `goods_adjust_price_item` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `adjust_id` BIGINT NOT NULL COMMENT '调价单ID',
    `goods_code` VARCHAR(64) NOT NULL COMMENT '商品编码',
    `goods_name` VARCHAR(128) DEFAULT NULL COMMENT '商品名称',
    `sku_code` VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    `goods_spec` VARCHAR(256) DEFAULT NULL COMMENT '商品规格',
    `goods_unit` VARCHAR(32) DEFAULT NULL COMMENT '单位',
    `old_price` DECIMAL(18,4) DEFAULT NULL COMMENT '原销售价',
    `new_price` DECIMAL(18,4) NOT NULL COMMENT '新销售价',
    `quantity` DECIMAL(18,4) DEFAULT NULL COMMENT '数量',
    `amount` DECIMAL(18,4) DEFAULT NULL COMMENT '金额',
    `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `sort_order` INT DEFAULT 0 COMMENT '排序序号',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    INDEX `idx_adjust_id` (`adjust_id`),
    INDEX `idx_sku_code` (`sku_code`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品调价单明细表';