CREATE TABLE IF NOT EXISTS `sale_order_main` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '閿€鍞鍗曠紪鍙?,
    `doc_name` VARCHAR(200) NOT NULL COMMENT '鍗曟嵁鍚嶇О锛堝繀濉紝榛樿锛氬崟鎹被鍨�+褰撳ぉ鏃ユ湡锛�',
    `customer_id` BIGINT DEFAULT NULL COMMENT '瀹㈡埛ID',
    `customer_code` VARCHAR(64) DEFAULT NULL COMMENT '瀹㈡埛缂栫爜',
    `customer_name` VARCHAR(255) DEFAULT NULL COMMENT '瀹㈡埛鍚嶇О',
    `order_date` VARCHAR(20) DEFAULT NULL COMMENT '璁㈠崟鏃ユ湡',
    `delivery_date` VARCHAR(20) DEFAULT NULL COMMENT '浜よ揣鏃ユ湡',
    `sale_type` TINYINT DEFAULT NULL COMMENT '閿€鍞被鍨嬶細1-鏅€氶攢鍞?2-鎵瑰彂 3-闆跺敭',
    `payment_type` TINYINT DEFAULT NULL COMMENT '浠樻鏂瑰紡锛?-鐜伴噾 2-鍒峰崱 3-璧婇攢',
    `currency_code` VARCHAR(10) DEFAULT NULL COMMENT '璐у竵缂栫爜',
    `exchange_rate` DECIMAL(12,4) DEFAULT NULL COMMENT '姹囩巼',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '璁㈠崟鎬婚噾棰濓紙涓嶅惈绋庯級',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `discount_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '鎶樻墸閲戦',
    `pay_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '瀹為檯鏀舵閲戦',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `warehouse_code` VARCHAR(64) DEFAULT NULL COMMENT '浠撳簱缂栫爜',
    `warehouse_name` VARCHAR(255) DEFAULT NULL COMMENT '浠撳簱鍚嶇О',
    `order_status` TINYINT DEFAULT 1 COMMENT '璁㈠崟鐘舵€侊細1-寰呭鎵?2-瀹℃牳閫氳繃 3-宸插叆搴?4-宸插彇娑?5-宸插畬鎴?,
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_customer_code` (`customer_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閿€鍞鍗曚富琛?;

CREATE TABLE IF NOT EXISTS `sale_order_item` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `order_id` BIGINT NOT NULL COMMENT '璁㈠崟涓昏〃ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '璁㈠崟缂栧彿',
    `item_no` INT DEFAULT NULL COMMENT '琛屽彿',
    `goods_id` BIGINT DEFAULT NULL COMMENT '鍟嗗搧ID',
    `goods_code` VARCHAR(64) DEFAULT NULL COMMENT '鍟嗗搧缂栫爜',
    `sku_code` VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
    `barcode` VARCHAR(64) DEFAULT NULL COMMENT '条码',
    `goods_name` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧鍚嶇О',
    `goods_spec` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧瑙勬牸鍨嬪彿',
    `unit_code` VARCHAR(32) DEFAULT NULL COMMENT '璁￠噺鍗曚綅缂栫爜',
    `goods_unit` VARCHAR(32) DEFAULT NULL COMMENT '商品单位名称',
    `conversion_rate` DECIMAL(18,4) DEFAULT 1.0000 COMMENT '销售单位到库存基础单位的换算率',
    `quantity` DECIMAL(18,4) NOT NULL COMMENT '閿€鍞暟閲?,
    `unit_price` DECIMAL(18,4) NOT NULL COMMENT '鍗曚环锛堜笉鍚◣锛?,
    `amount` DECIMAL(18,4) DEFAULT NULL COMMENT '閲戦锛堜笉鍚◣锛?,
    `tax_rate` DECIMAL(8,4) DEFAULT NULL COMMENT '绋庣巼',
    `is_tax_inclusive` TINYINT DEFAULT 0 COMMENT '标价是否含税(0:否 1:是)',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `discount_rate` DECIMAL(8,4) DEFAULT NULL COMMENT '鎶樻墸鐜?,
    `discount_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '鎶樻墸閲戦',
    `net_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '鍑€閲戦锛堝惈绋庯級',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_goods_code` (`goods_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閿€鍞鍗曟槑缁?;

CREATE TABLE IF NOT EXISTS `sale_out_main` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `out_no` VARCHAR(64) NOT NULL COMMENT '鍑哄簱鍗曠紪鍙?,
    `doc_name` VARCHAR(200) NOT NULL COMMENT '鍗曟嵁鍚嶇О锛堝繀濉紝榛樿锛氬崟鎹被鍨�+褰撳ぉ鏃ユ湡锛�',
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈閿€鍞鍗曠紪鍙?,
    `customer_id` BIGINT DEFAULT NULL COMMENT '瀹㈡埛ID',
    `customer_code` VARCHAR(64) DEFAULT NULL COMMENT '瀹㈡埛缂栫爜',
    `customer_name` VARCHAR(255) DEFAULT NULL COMMENT '瀹㈡埛鍚嶇О',
    `out_date` VARCHAR(20) DEFAULT NULL COMMENT '鍑哄簱鏃ユ湡',
    `warehouse_code` VARCHAR(64) DEFAULT NULL COMMENT '浠撳簱缂栫爜',
    `warehouse_name` VARCHAR(255) DEFAULT NULL COMMENT '浠撳簱鍚嶇О',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '鍑哄簱鎬婚噾棰濓紙涓嶅惈绋庯級',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_out_no` (`out_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_customer_code` (`customer_code`),
    KEY `idx_warehouse_code` (`warehouse_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閿€鍞嚭搴撲富琛?;

CREATE TABLE IF NOT EXISTS `sale_out_item` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `out_id` BIGINT NOT NULL COMMENT '鍑哄簱鍗曚富琛↖D',
    `out_no` VARCHAR(64) NOT NULL COMMENT '鍑哄簱鍗曠紪鍙?,
    `order_id` BIGINT DEFAULT NULL COMMENT '鍏宠仈閿€鍞鍗旾D',
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈閿€鍞鍗曠紪鍙?,
    `item_no` INT DEFAULT NULL COMMENT '琛屽彿',
    `goods_id` BIGINT DEFAULT NULL COMMENT '鍟嗗搧ID',
    `goods_code` VARCHAR(64) DEFAULT NULL COMMENT '鍟嗗搧缂栫爜',
    `sku_code` VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
    `barcode` VARCHAR(64) DEFAULT NULL COMMENT '条码',
    `goods_name` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧鍚嶇О',
    `goods_spec` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧瑙勬牸鍨嬪彿',
    `unit_code` VARCHAR(32) DEFAULT NULL COMMENT '璁￠噺鍗曚綅缂栫爜',
    `goods_unit` VARCHAR(32) DEFAULT NULL COMMENT '商品单位名称',
    `conversion_rate` DECIMAL(18,4) DEFAULT 1.0000 COMMENT '销售单位到库存基础单位的换算率',
    `order_quantity` DECIMAL(18,4) DEFAULT NULL COMMENT '璁㈠崟鏁伴噺',
    `out_quantity` DECIMAL(18,4) NOT NULL COMMENT '瀹為檯鍑哄簱鏁伴噺',
    `unit_price` DECIMAL(18,4) NOT NULL COMMENT '鍗曚环锛堜笉鍚◣锛?,
    `amount` DECIMAL(18,4) DEFAULT NULL COMMENT '閲戦锛堜笉鍚◣锛?,
    `tax_rate` DECIMAL(8,4) DEFAULT NULL COMMENT '绋庣巼',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `batch_no` VARCHAR(64) DEFAULT NULL COMMENT '鎵规鍙?,
    `expire_date` VARCHAR(20) DEFAULT NULL COMMENT '鏈夋晥鏈?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    KEY `idx_out_id` (`out_id`),
    KEY `idx_out_no` (`out_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_goods_code` (`goods_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閿€鍞嚭搴撴槑缁?;

CREATE TABLE IF NOT EXISTS `sale_return_main` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `return_no` VARCHAR(64) NOT NULL COMMENT '閿€鍞€€璐у崟缂栧彿',
    `doc_name` VARCHAR(200) NOT NULL COMMENT '鍗曟嵁鍚嶇О锛堝繀濉紝榛樿锛氬崟鎹被鍨�+褰撳ぉ鏃ユ湡锛�',
    `out_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈鍑哄簱鍗曠紪鍙?,
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈閿€鍞鍗曠紪鍙?,
    `customer_id` BIGINT DEFAULT NULL COMMENT '瀹㈡埛ID',
    `customer_code` VARCHAR(64) DEFAULT NULL COMMENT '瀹㈡埛缂栫爜',
    `customer_name` VARCHAR(255) DEFAULT NULL COMMENT '瀹㈡埛鍚嶇О',
    `return_date` VARCHAR(20) DEFAULT NULL COMMENT '閫€璐ф棩鏈?,
    `warehouse_code` VARCHAR(64) DEFAULT NULL COMMENT '浠撳簱缂栫爜',
    `warehouse_name` VARCHAR(255) DEFAULT NULL COMMENT '浠撳簱鍚嶇О',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '閫€璐ф€婚噾棰濓紙涓嶅惈绋庯級',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `pay_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '瀹為檯閫€娆鹃噾棰?,
    `return_reason` VARCHAR(500) DEFAULT NULL COMMENT '閫€璐у師鍥?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_return_no` (`return_no`),
    KEY `idx_out_no` (`out_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_customer_code` (`customer_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閿€鍞€€璐т富琛?;

CREATE TABLE IF NOT EXISTS `sale_return_item` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `return_id` BIGINT NOT NULL COMMENT '閫€璐у崟涓昏〃ID',
    `return_no` VARCHAR(64) NOT NULL COMMENT '閫€璐у崟缂栧彿',
    `out_id` BIGINT DEFAULT NULL COMMENT '鍏宠仈鍑哄簱鍗旾D',
    `out_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈鍑哄簱鍗曠紪鍙?,
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈閿€鍞鍗曠紪鍙?,
    `item_no` INT DEFAULT NULL COMMENT '琛屽彿',
    `goods_id` BIGINT DEFAULT NULL COMMENT '鍟嗗搧ID',
    `goods_code` VARCHAR(64) DEFAULT NULL COMMENT '鍟嗗搧缂栫爜',
    `sku_code` VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
    `barcode` VARCHAR(64) DEFAULT NULL COMMENT '条码',
    `goods_name` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧鍚嶇О',
    `goods_spec` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧瑙勬牸鍨嬪彿',
    `unit_code` VARCHAR(32) DEFAULT NULL COMMENT '璁￠噺鍗曚綅缂栫爜',
    `goods_unit` VARCHAR(32) DEFAULT NULL COMMENT '商品单位名称',
    `conversion_rate` DECIMAL(18,4) DEFAULT 1.0000 COMMENT '销售单位到库存基础单位的换算率',
    `out_quantity` DECIMAL(18,4) DEFAULT NULL COMMENT '鍑哄簱鏁伴噺',
    `return_quantity` DECIMAL(18,4) NOT NULL COMMENT '閫€璐ф暟閲?,
    `unit_price` DECIMAL(18,4) NOT NULL COMMENT '鍗曚环锛堜笉鍚◣锛?,
    `amount` DECIMAL(18,4) DEFAULT NULL COMMENT '閲戦锛堜笉鍚◣锛?,
    `tax_rate` DECIMAL(8,4) DEFAULT NULL COMMENT '绋庣巼',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `batch_no` VARCHAR(64) DEFAULT NULL COMMENT '鎵规鍙?,
    `expire_date` VARCHAR(20) DEFAULT NULL COMMENT '鏈夋晥鏈?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    KEY `idx_return_id` (`return_id`),
    KEY `idx_return_no` (`return_no`),
    KEY `idx_out_no` (`out_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_goods_code` (`goods_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閿€鍞€€璐ф槑缁?;

CREATE TABLE IF NOT EXISTS `customer` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `customer_code` VARCHAR(64) NOT NULL COMMENT '瀹㈡埛缂栫爜',
    `customer_name` VARCHAR(255) NOT NULL COMMENT '瀹㈡埛鍏ㄧО',
    `short_name` VARCHAR(100) DEFAULT NULL COMMENT '瀹㈡埛绠€绉?,
    `contact_name` VARCHAR(100) DEFAULT NULL COMMENT '鑱旂郴浜哄鍚?,
    `contact_phone` VARCHAR(50) DEFAULT NULL COMMENT '鑱旂郴浜虹數璇?,
    `email` VARCHAR(100) DEFAULT NULL COMMENT '鐢靛瓙閭',
    `address` VARCHAR(500) DEFAULT NULL COMMENT '璇︾粏鍦板潃',
    `province` VARCHAR(100) DEFAULT NULL COMMENT '鐪佷唤',
    `city` VARCHAR(100) DEFAULT NULL COMMENT '鍩庡競',
    `district` VARCHAR(100) DEFAULT NULL COMMENT '鍖哄幙',
    `zip_code` VARCHAR(20) DEFAULT NULL COMMENT '閭斂缂栫爜',
    `tax_no` VARCHAR(50) DEFAULT NULL COMMENT '绋庡姟鐧昏鍙?,
    `bank_name` VARCHAR(100) DEFAULT NULL COMMENT '寮€鎴烽摱琛屽悕绉?,
    `bank_account` VARCHAR(50) DEFAULT NULL COMMENT '閾惰璐﹀彿',
    `customer_type` VARCHAR(20) DEFAULT NULL COMMENT '瀹㈡埛绫诲瀷锛?-鏅€氬鎴?2-浼氬憳 3-鎵瑰彂鍟?,
    `customer_level` VARCHAR(10) DEFAULT NULL COMMENT '瀹㈡埛绛夌骇锛欰/B/C/D',
    `credit_limit` DECIMAL(18,4) DEFAULT NULL COMMENT '淇＄敤棰濆害',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_customer_code` (`customer_code`),
    KEY `idx_customer_name` (`customer_name`),
    KEY `idx_customer_type` (`customer_type`),
    KEY `idx_customer_level` (`customer_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡埛琛?;

CREATE TABLE IF NOT EXISTS `customer_debt` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `customer_id` BIGINT NOT NULL COMMENT '瀹㈡埛ID',
    `customer_code` VARCHAR(64) DEFAULT NULL COMMENT '瀹㈡埛缂栫爜',
    `customer_name` VARCHAR(255) DEFAULT NULL COMMENT '瀹㈡埛鍚嶇О',
    `total_debt_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绱娆犳閲戦',
    `paid_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '宸茶繕娆鹃噾棰?,
    `pending_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '寰呰繕娆鹃噾棰濓紙娆犳浣欓锛?,
    `credit_limit` DECIMAL(18,4) DEFAULT NULL COMMENT '淇＄敤棰濆害',
    `available_credit` DECIMAL(18,4) DEFAULT NULL COMMENT '鍙敤淇＄敤棰濆害',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_customer_id` (`customer_id`),
    KEY `idx_customer_code` (`customer_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡埛娆犳姹囨€昏〃';

CREATE TABLE IF NOT EXISTS `customer_debt_detail` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `customer_id` BIGINT NOT NULL COMMENT '瀹㈡埛ID',
    `customer_code` VARCHAR(64) DEFAULT NULL COMMENT '瀹㈡埛缂栫爜',
    `customer_name` VARCHAR(255) DEFAULT NULL COMMENT '瀹㈡埛鍚嶇О',
    `bill_type` TINYINT DEFAULT NULL COMMENT '鍏宠仈鍗曟嵁绫诲瀷锛?-閿€鍞鍗?2-閿€鍞嚭搴?,
    `bill_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈鍗曟嵁缂栧彿',
    `debt_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '娆犳閲戦',
    `paid_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '宸茶繕閲戦',
    `pending_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '寰呰繕閲戦',
    `debt_date` VARCHAR(20) DEFAULT NULL COMMENT '娆犳鏃ユ湡',
    `due_date` VARCHAR(20) DEFAULT NULL COMMENT '鍒版湡鏃ユ湡',
    `status` TINYINT DEFAULT NULL COMMENT '鐘舵€侊細1-寰呰繕娆?2-閮ㄥ垎杩樻 3-宸茬粨娓?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_customer_code` (`customer_code`),
    KEY `idx_bill_no` (`bill_no`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡埛娆犳鏄庣粏琛?;

CREATE TABLE IF NOT EXISTS `customer_payment` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `payment_no` VARCHAR(64) NOT NULL COMMENT '杩樻鍗曠紪鍙?,
    `customer_id` BIGINT NOT NULL COMMENT '瀹㈡埛ID',
    `customer_code` VARCHAR(64) DEFAULT NULL COMMENT '瀹㈡埛缂栫爜',
    `customer_name` VARCHAR(255) DEFAULT NULL COMMENT '瀹㈡埛鍚嶇О',
    `payment_date` VARCHAR(20) DEFAULT NULL COMMENT '杩樻鏃ユ湡',
    `payment_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '杩樻閲戦',
    `payment_method` TINYINT DEFAULT NULL COMMENT '杩樻鏂瑰紡锛?-鐜伴噾 2-閾惰杞处 3-鏀粯瀹?4-寰俊 5-鍏朵粬',
    `account_no` VARCHAR(100) DEFAULT NULL COMMENT '鏀舵璐︽埛',
    `bank_name` VARCHAR(100) DEFAULT NULL COMMENT '鏀舵閾惰',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_payment_no` (`payment_no`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_customer_code` (`customer_code`),
    KEY `idx_payment_method` (`payment_method`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='瀹㈡埛杩樻琛?;

-- 同步日志表：记录客户数据最后同步时间，用于增量同步
CREATE TABLE IF NOT EXISTS `sync_log` (
    `data_uuid`           VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成）',
    `tenant_id`           VARCHAR(50) NOT NULL,
    `type`                VARCHAR(10) NOT NULL,
    `last_download_time`  VARCHAR(20) DEFAULT NULL COMMENT '最后同步时间',
    PRIMARY KEY (`tenant_id`, `type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='同步日志表';

