-- psi-common-starter-order-rule 通用草稿单据模块 建表脚本
-- 适用于采购、销售、退货、报损、报溢、盘点等所有业务单据的草稿
-- 通过 doc_type 字段区分不同单据类型，审批通过后转为各业务正式表

-- 单据主表（草稿表，审批通过后转为各业务的正式表）
CREATE TABLE IF NOT EXISTS doc_main_draft (
    id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    data_uuid VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    shop_code VARCHAR(64) DEFAULT NULL COMMENT '商铺编码',
    shop_name VARCHAR(200) DEFAULT NULL COMMENT '商铺名称',
    doc_no VARCHAR(64) NOT NULL COMMENT '单据编号（自动生成）',
    doc_type VARCHAR(32) NOT NULL COMMENT '单据类型：PURCHASE_ORDER-采购订单 PURCHASE_IN-采购入库 PURCHASE_RETURN-采购退货 SALE_ORDER-销售订单 SALE_OUT-销售出库 SALE_RETURN-销售退货 STOCK_LOSS-报损单 STOCK_OVERFLOW-报溢单 STOCK_CHECK-盘点单 STOCK_TRANSFER-调拨单',
    status INT DEFAULT 0 COMMENT '单据状态：0-草稿 1-已提交 2-审批中 3-已审批 4-执行中 5-已完成 -1-已取消 -2-已驳回',
    creator_id VARCHAR(64) DEFAULT NULL COMMENT '创建人ID',
    creator_name VARCHAR(100) DEFAULT NULL COMMENT '创建人姓名',
    dept_id VARCHAR(64) DEFAULT NULL COMMENT '部门ID',
    dept_name VARCHAR(100) DEFAULT NULL COMMENT '部门名称',
    partner_id VARCHAR(64) DEFAULT NULL COMMENT '供应商/客户ID（根据单据类型使用）',
    partner_code VARCHAR(64) DEFAULT NULL COMMENT '供应商/客户编码',
    partner_name VARCHAR(200) DEFAULT NULL COMMENT '供应商/客户名称',
    warehouse_id BIGINT DEFAULT NULL COMMENT '仓库ID',
    warehouse_code VARCHAR(64) DEFAULT NULL COMMENT '仓库编码',
    warehouse_name VARCHAR(100) DEFAULT NULL COMMENT '仓库名称',
    order_no VARCHAR(64) DEFAULT NULL COMMENT '关联订单号（用于入库/出库等关联上游单据）',
    sale_type INT DEFAULT NULL COMMENT '销售类型：1-普通销售 2-批发 3-零售',
    payment_type INT DEFAULT NULL COMMENT '付款方式：1-预付定金 2-货到付款 3-月结 4-现金 5-刷卡 6-赊销',
    currency_code VARCHAR(32) DEFAULT 'CNY' COMMENT '货币编码',
    exchange_rate DECIMAL(12,4) DEFAULT 1.0000 COMMENT '汇率',
    total_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '总金额（不含税）',
    tax_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '税额',
    discount_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '折扣金额',
    pay_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '实付/实收金额',
    item_count INT DEFAULT 0 COMMENT '明细数量',
    doc_date DATETIME DEFAULT NULL COMMENT '单据日期',
    delivery_date DATETIME DEFAULT NULL COMMENT '交货/预计到货日期',
    audit_status INT DEFAULT 0 COMMENT '审核状态：0-未审核 1-已审核 2-审核驳回',
    audit_by BIGINT DEFAULT NULL COMMENT '审核人ID',
    approve_time DATETIME DEFAULT NULL COMMENT '审批时间',
    execute_time DATETIME DEFAULT NULL COMMENT '执行时间',
    complete_time DATETIME DEFAULT NULL COMMENT '完成时间',
    cancel_time DATETIME DEFAULT NULL COMMENT '取消时间',
    doc_name VARCHAR(200) NOT NULL COMMENT '单据名称（必填，默认：单据类型+当天日期）',
    
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    ext_json TEXT COMMENT '扩展字段（JSON格式，存储单据类型特有字段如报损原因、调拨出入库等）',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标识 0-未删除 1-已删除',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人ID',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_data_uuid (data_uuid),
    UNIQUE KEY uk_doc_no (doc_no),
    INDEX idx_doc_type (doc_type),
    INDEX idx_status (status),
    INDEX idx_partner_id (partner_id),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_creator_id (creator_id),
    INDEX idx_doc_date (doc_date),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_shop_code (shop_code),
    INDEX idx_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单据草稿主表（采购、销售、退货、报损、报溢、盘点等通用草稿）';

-- 单据明细表（草稿表）
CREATE TABLE IF NOT EXISTS doc_item_draft (
    id BIGINT AUTO_INCREMENT COMMENT '主键ID',
    data_uuid VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    shop_code VARCHAR(64) DEFAULT NULL COMMENT '商铺编码',
    shop_name VARCHAR(200) DEFAULT NULL COMMENT '商铺名称',
    doc_id BIGINT NOT NULL COMMENT '草稿主表ID',
    doc_no VARCHAR(64) DEFAULT NULL COMMENT '单据编号',
    goods_id BIGINT DEFAULT NULL COMMENT '商品ID',
    goods_code VARCHAR(64) DEFAULT NULL COMMENT '商品编码',
    sku_code VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    sku_name VARCHAR(200) DEFAULT NULL COMMENT 'SKU名称',
    barcode VARCHAR(64) DEFAULT NULL COMMENT '条码',
    goods_name VARCHAR(200) DEFAULT NULL COMMENT '商品名称',
    goods_spec VARCHAR(200) DEFAULT NULL COMMENT '商品规格',
    unit_code VARCHAR(32) DEFAULT NULL COMMENT '计量单位编码',
    goods_unit VARCHAR(32) DEFAULT NULL COMMENT '商品单位名称',
    conversion_rate DECIMAL(18,4) DEFAULT 1.0000 COMMENT '销售单位到库存基础单位的换算率',
    unit_price DECIMAL(18,2) DEFAULT 0.00 COMMENT '单价（不含税）',
    quantity DECIMAL(18,2) DEFAULT 0.00 COMMENT '数量',
    amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '金额（不含税，单价*数量）',
    tax_rate DECIMAL(12,2) DEFAULT 0.00 COMMENT '税率(%)',
    tax_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '税额',
    discount_rate DECIMAL(12,2) DEFAULT 0.00 COMMENT '折扣率(%)',
    discount_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '折扣金额',
    
net_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '净金额（含税）',
    cost_price DECIMAL(18,2) DEFAULT 0.00 COMMENT '成本价',
    cost_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '成本金额',
    pay_amount DECIMAL(18,2) DEFAULT 0.00 COMMENT '实付金额',
    stock_id BIGINT DEFAULT NULL COMMENT '库存ID',
    batch_no VARCHAR(64) DEFAULT NULL COMMENT '批次号',
    expiry_date VARCHAR(32) DEFAULT NULL COMMENT '有效期至',
    line_no INT DEFAULT 0 COMMENT '行号',
    
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标识 0-未删除 1-已删除',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人ID',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_data_uuid (data_uuid),
    INDEX idx_doc_id (doc_id),
    INDEX idx_doc_no (doc_no),
    INDEX idx_goods_id (goods_id),
    INDEX idx_goods_code (goods_code),
    INDEX idx_shop_code (shop_code),
    INDEX idx_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单据明细草稿表';