-- 自用出库正式表
CREATE TABLE IF NOT EXISTS sale_out_self_use_main (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    data_uuid VARCHAR(64) DEFAULT NULL COMMENT '数据UUID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    out_no VARCHAR(64) NOT NULL COMMENT '出库单编号',
    doc_name VARCHAR(200) NOT NULL DEFAULT '' COMMENT '单据名称',
    customer_id BIGINT DEFAULT NULL COMMENT '客户ID',
    customer_code VARCHAR(64) DEFAULT NULL COMMENT '客户编码',
    customer_name VARCHAR(255) DEFAULT NULL COMMENT '客户名称',
    out_date VARCHAR(20) DEFAULT NULL COMMENT '出库日期',
    warehouse_code VARCHAR(64) DEFAULT NULL COMMENT '仓库编码',
    warehouse_name VARCHAR(255) DEFAULT NULL COMMENT '仓库名称',
    total_amount DECIMAL(18,4) DEFAULT NULL COMMENT '出库总金额（不含税）',
    tax_amount DECIMAL(18,4) DEFAULT NULL COMMENT '税额',
    self_use_reason VARCHAR(500) DEFAULT NULL COMMENT '自用原因',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人ID',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    del_flag TINYINT DEFAULT '0' COMMENT '删除标记(0:未删除 1:已删除)',
    status TINYINT DEFAULT '1' COMMENT '状态: 1-待审批 2-审核通过 3-已完成 4-已取消',
    PRIMARY KEY (id),
    UNIQUE KEY uk_out_no (out_no),
    UNIQUE KEY uk_data_uuid (data_uuid),
    KEY idx_customer_code (customer_code),
    KEY idx_warehouse_code (warehouse_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='自用出库主表';

-- 自用出库明细表
CREATE TABLE IF NOT EXISTS sale_out_self_use_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    data_uuid VARCHAR(64) DEFAULT NULL COMMENT '数据UUID',
    tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
    out_id BIGINT NOT NULL COMMENT '出库单主表ID',
    out_no VARCHAR(64) NOT NULL COMMENT '出库单编号',
    item_no INT DEFAULT NULL COMMENT '行号',
    goods_id BIGINT DEFAULT NULL COMMENT '商品ID',
    goods_code VARCHAR(64) DEFAULT NULL COMMENT '商品编码',
    sku_code VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    sku_name VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
    goods_name VARCHAR(255) DEFAULT NULL COMMENT '商品名称',
    goods_spec VARCHAR(255) DEFAULT NULL COMMENT '商品规格型号',
    unit_code VARCHAR(32) DEFAULT NULL COMMENT '计量单位编码',
    conversion_rate DECIMAL(18,6) DEFAULT '1.000000' COMMENT '销售单位到库存基础单位的换算率',
    out_quantity DECIMAL(18,4) NOT NULL COMMENT '实际出库数量',
    unit_price DECIMAL(18,4) NOT NULL COMMENT '单价（不含税）',
    amount DECIMAL(18,4) DEFAULT NULL COMMENT '金额（不含税）',
    tax_rate DECIMAL(8,4) DEFAULT NULL COMMENT '税率',
    tax_amount DECIMAL(18,4) DEFAULT NULL COMMENT '税额',
    batch_no VARCHAR(64) DEFAULT NULL COMMENT '批次号',
    expire_date VARCHAR(20) DEFAULT NULL COMMENT '有效期',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_by BIGINT DEFAULT NULL COMMENT '更新人ID',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    del_flag TINYINT DEFAULT '0' COMMENT '删除标记(0:未删除 1:已删除)',
    status TINYINT DEFAULT '1' COMMENT '状态: 1-待审批 2-审核通过 3-已完成 4-已取消',
    PRIMARY KEY (id),
    UNIQUE KEY uk_data_uuid (data_uuid),
    KEY idx_out_id (out_id),
    KEY idx_out_no (out_no),
    KEY idx_goods_code (goods_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='自用出库明细表';
