CREATE TABLE IF NOT EXISTS `finance_receivable` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `store_code` VARCHAR(64) NOT NULL COMMENT '门店编码',
    `store_name` VARCHAR(128) DEFAULT NULL COMMENT '门店名称',
    `customer_id` BIGINT DEFAULT NULL COMMENT '客户ID',
    `customer_code` VARCHAR(64) DEFAULT NULL COMMENT '客户编码',
    `customer_name` VARCHAR(128) DEFAULT NULL COMMENT '客户名称',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '总金额',
    `paid_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '已付金额',
    `remain_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '剩余金额',
    `source_no` VARCHAR(64) DEFAULT NULL COMMENT '来源单据编号',
    `source_type` VARCHAR(64) DEFAULT NULL COMMENT '来源单据类型',
    `bill_date` VARCHAR(20) DEFAULT NULL COMMENT '单据日期',
    `due_date` VARCHAR(20) DEFAULT NULL COMMENT '到期日期',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_store_code` (`store_code`),
    INDEX `idx_customer_code` (`customer_code`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应收款表';

CREATE TABLE IF NOT EXISTS `finance_receivable_pay` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `store_code` VARCHAR(64) NOT NULL COMMENT '门店编码',
    `store_name` VARCHAR(128) DEFAULT NULL COMMENT '门店名称',
    `receivable_id` BIGINT NOT NULL COMMENT '应收款ID',
    `customer_code` VARCHAR(64) DEFAULT NULL COMMENT '客户编码',
    `customer_name` VARCHAR(128) DEFAULT NULL COMMENT '客户名称',
    `pay_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '付款金额',
    `pay_method` VARCHAR(32) DEFAULT NULL COMMENT '付款方式(CASH/WECHAT/ALIPAY/BANK)',
    `pay_no` VARCHAR(64) DEFAULT NULL COMMENT '付款流水号',
    `pay_date` VARCHAR(20) DEFAULT NULL COMMENT '付款日期',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`),
    INDEX `idx_store_code` (`store_code`),
    INDEX `idx_receivable_id` (`receivable_id`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应收款还款记录表';

CREATE TABLE IF NOT EXISTS `finance_payable` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `store_code` VARCHAR(64) NOT NULL COMMENT '门店编码',
    `store_name` VARCHAR(128) DEFAULT NULL COMMENT '门店名称',
    `supplier_id` BIGINT DEFAULT NULL COMMENT '供应商ID',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '供应商编码',
    `supplier_name` VARCHAR(128) DEFAULT NULL COMMENT '供应商名称',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '总金额',
    `paid_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '已付金额',
    `remain_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '剩余金额',
    `source_no` VARCHAR(64) DEFAULT NULL COMMENT '来源单据编号',
    `source_type` VARCHAR(64) DEFAULT NULL COMMENT '来源单据类型',
    `bill_date` VARCHAR(20) DEFAULT NULL COMMENT '单据日期',
    `due_date` VARCHAR(20) DEFAULT NULL COMMENT '到期日期',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_store_code` (`store_code`),
    INDEX `idx_supplier_code` (`supplier_code`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应付款表';

CREATE TABLE IF NOT EXISTS `finance_payable_pay` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `store_code` VARCHAR(64) NOT NULL COMMENT '门店编码',
    `store_name` VARCHAR(128) DEFAULT NULL COMMENT '门店名称',
    `payable_id` BIGINT NOT NULL COMMENT '应付款ID',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '供应商编码',
    `supplier_name` VARCHAR(128) DEFAULT NULL COMMENT '供应商名称',
    `pay_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '付款金额',
    `pay_method` VARCHAR(32) DEFAULT NULL COMMENT '付款方式(CASH/WECHAT/ALIPAY/BANK)',
    `pay_no` VARCHAR(64) DEFAULT NULL COMMENT '付款流水号',
    `pay_date` VARCHAR(20) DEFAULT NULL COMMENT '付款日期',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`),
    INDEX `idx_store_code` (`store_code`),
    INDEX `idx_payable_id` (`payable_id`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应付款付款记录表';

CREATE TABLE IF NOT EXISTS `finance_account` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `store_code` VARCHAR(64) NOT NULL COMMENT '门店编码',
    `store_name` VARCHAR(128) DEFAULT NULL COMMENT '门店名称',
    `account_type` VARCHAR(32) NOT NULL COMMENT '账户类型(CASH/WECHAT/ALIPAY/BANK)',
    `account_name` VARCHAR(128) DEFAULT NULL COMMENT '账户名称',
    `account_no` VARCHAR(64) DEFAULT NULL COMMENT '账户号码',
    `balance` DECIMAL(18,4) DEFAULT NULL COMMENT '账户余额',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_store_account` (`store_code`, `account_type`),
    INDEX `idx_store_code` (`store_code`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资金账户表';

CREATE TABLE IF NOT EXISTS `finance_account_flow` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `store_code` VARCHAR(64) NOT NULL COMMENT '门店编码',
    `store_name` VARCHAR(128) DEFAULT NULL COMMENT '门店名称',
    `account_type` VARCHAR(32) NOT NULL COMMENT '账户类型',
    `account_name` VARCHAR(128) DEFAULT NULL COMMENT '账户名称',
    `flow_type` TINYINT DEFAULT 0 COMMENT '流水类型(1:收入 2:支出)',
    `in_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '收入金额',
    `out_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '支出金额',
    `balance_before` DECIMAL(18,4) DEFAULT NULL COMMENT '变动前余额',
    `balance_after` DECIMAL(18,4) DEFAULT NULL COMMENT '变动后余额',
    `source_no` VARCHAR(64) DEFAULT NULL COMMENT '来源单据编号',
    `source_type` VARCHAR(64) DEFAULT NULL COMMENT '来源单据类型',
    `pay_no` VARCHAR(64) DEFAULT NULL COMMENT '支付流水号',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`),
    INDEX `idx_store_code` (`store_code`),
    INDEX `idx_account_type` (`account_type`),
    INDEX `idx_create_time` (`create_time`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资金账户流水表';

CREATE TABLE IF NOT EXISTS `finance_daily_ledger` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `store_code` VARCHAR(64) NOT NULL COMMENT '门店编码',
    `store_name` VARCHAR(128) DEFAULT NULL COMMENT '门店名称',
    `ledger_date` VARCHAR(20) NOT NULL COMMENT '台账日期',
    `sale_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '销售金额',
    `cost_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '成本金额',
    `profit_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '利润金额',
    `cash_in` DECIMAL(18,4) DEFAULT NULL COMMENT '现金收入',
    `cash_out` DECIMAL(18,4) DEFAULT NULL COMMENT '现金支出',
    `transfer_in` DECIMAL(18,4) DEFAULT NULL COMMENT '转账收入',
    `transfer_out` DECIMAL(18,4) DEFAULT NULL COMMENT '转账支出',
    `receivable_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '应收金额',
    `payable_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '应付金额',
    `beginning_balance` DECIMAL(18,4) DEFAULT NULL COMMENT '期初余额',
    `ending_balance` DECIMAL(18,4) DEFAULT NULL COMMENT '期末余额',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_store_date` (`store_code`, `ledger_date`),
    INDEX `idx_store_code` (`store_code`),
    INDEX `idx_ledger_date` (`ledger_date`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店台账日报表';

CREATE TABLE IF NOT EXISTS `finance_daily_close` (
    `id` BIGINT AUTO_INCREMENT COMMENT '主键ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `store_code` VARCHAR(64) NOT NULL COMMENT '门店编码',
    `store_name` VARCHAR(128) DEFAULT NULL COMMENT '门店名称',
    `close_date` VARCHAR(20) NOT NULL COMMENT '日结日期',
    `sale_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '销售金额',
    `cost_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '成本金额',
    `profit_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '利润金额',
    `cash_in` DECIMAL(18,4) DEFAULT NULL COMMENT '现金收入',
    `cash_out` DECIMAL(18,4) DEFAULT NULL COMMENT '现金支出',
    `transfer_in` DECIMAL(18,4) DEFAULT NULL COMMENT '转账收入',
    `transfer_out` DECIMAL(18,4) DEFAULT NULL COMMENT '转账支出',
    `receivable_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '应收金额',
    `payable_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '应付金额',
    `cash_balance` DECIMAL(18,4) DEFAULT NULL COMMENT '现金账户余额',
    `wechat_balance` DECIMAL(18,4) DEFAULT NULL COMMENT '微信账户余额',
    `alipay_balance` DECIMAL(18,4) DEFAULT NULL COMMENT '支付宝账户余额',
    `bank_balance` DECIMAL(18,4) DEFAULT NULL COMMENT '对公账户余额',
    `total_balance` DECIMAL(18,4) DEFAULT NULL COMMENT '总余额',
    `close_by` VARCHAR(64) DEFAULT NULL COMMENT '日结人',
    `close_time` VARCHAR(30) DEFAULT NULL COMMENT '日结时间',
    `close_status` TINYINT DEFAULT 0 COMMENT '日结状态(0:未日结 1:已日结 2:已撤销)',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `del_flag` TINYINT DEFAULT 0 COMMENT '删除标识(0:未删除 1:已删除)',
    `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_store_close_date` (`store_code`, `close_date`),
    INDEX `idx_store_code` (`store_code`),
    INDEX `idx_close_date` (`close_date`),
    INDEX `idx_close_status` (`close_status`),
    INDEX `idx_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店日结表';