ALTER TABLE `customer_journey_config` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `customer_journey_config` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `customer_journey_config` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `customer_journey_config_bak_20260807` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `customer_journey_config_bak_20260807` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `customer_journey_config_bak_20260807` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `customer_journey_stage` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `customer_journey_stage` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `customer_journey_stage` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `customer_journey_state` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `customer_journey_state` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `customer_journey_state` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `customer_journey_template` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `customer_journey_template` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `customer_journey_template` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `customer_metrics` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `customer_metrics` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `customer_metrics` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `customer_touchpoint` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `customer_touchpoint` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `customer_touchpoint` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `doc_item_draft` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `down_sync` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `down_sync` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `down_sync` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `down_sync` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `finance_account` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `finance_account_flow` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `finance_account_flow` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `finance_account_flow` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `finance_daily_close` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `finance_daily_ledger` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `finance_daily_ledger` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `finance_daily_ledger` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `finance_payable` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `finance_payable_pay` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `finance_payable_pay` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `finance_payable_pay` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `finance_receivable_pay` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `finance_receivable_pay` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `finance_receivable_pay` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `goods_adjust_price_item` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `journey_dict` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `journey_dict` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `journey_dict` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `journey_rule_fire_log` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `journey_rule_fire_log` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `journey_rule_fire_log` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `journey_rule_fire_log` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `promotion_item` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `sync_log` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `sync_log` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `sync_log` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `sync_log` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `touchpoint_generate_rule` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `touchpoint_generate_rule` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `touchpoint_generate_rule` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `up_sync` ADD COLUMN `create_by` BIGINT NULL COMMENT '创建人';
ALTER TABLE `up_sync` ADD COLUMN `status` TINYINT NULL DEFAULT 1 COMMENT '状态';
ALTER TABLE `up_sync` ADD COLUMN `update_by` BIGINT NULL COMMENT '更新人';
ALTER TABLE `up_sync` ADD COLUMN `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
