ALTER TABLE member_balance_log
  ADD COLUMN create_by BIGINT NULL COMMENT '创建人',
  ADD COLUMN update_by BIGINT NULL COMMENT '更新人',
  ADD COLUMN update_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN status TINYINT NULL DEFAULT 1 COMMENT '状态';

ALTER TABLE member_point_log
  ADD COLUMN create_by BIGINT NULL COMMENT '创建人',
  ADD COLUMN update_by BIGINT NULL COMMENT '更新人',
  ADD COLUMN update_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  ADD COLUMN status TINYINT NULL DEFAULT 1 COMMENT '状态';

SELECT 'DONE' AS result;
