CREATE TABLE IF NOT EXISTS `purchase_order_main` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '閲囪喘璁㈠崟缂栧彿',
    `doc_name` VARCHAR(200) NOT NULL COMMENT '鍗曟嵁鍚嶇О锛堝繀濉紝榛樿锛氬崟鎹被鍨�+褰撳ぉ鏃ユ湡锛�',
    `supplier_id` BIGINT DEFAULT NULL COMMENT '渚涘簲鍟咺D',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '渚涘簲鍟嗙紪鐮?,
    `supplier_name` VARCHAR(255) DEFAULT NULL COMMENT '渚涘簲鍟嗗悕绉?,
    `order_date` VARCHAR(20) DEFAULT NULL COMMENT '璁㈠崟鏃ユ湡',
    `delivery_date` VARCHAR(20) DEFAULT NULL COMMENT '棰勮浜よ揣鏃ユ湡',
    `payment_type` TINYINT DEFAULT NULL COMMENT '浠樻鏂瑰紡锛?-棰勪粯瀹氶噾 2-璐у埌浠樻 3-鏈堢粨',
    `currency_code` VARCHAR(10) DEFAULT NULL COMMENT '璐у竵缂栫爜',
    `exchange_rate` DECIMAL(12,4) DEFAULT NULL COMMENT '姹囩巼',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '璁㈠崟鎬婚噾棰濓紙涓嶅惈绋庯級',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `discount_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '鎶樻墸閲戦',
    `pay_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '瀹為檯浠樻閲戦',
    `order_status` TINYINT DEFAULT NULL COMMENT '璁㈠崟鐘舵€侊細1-寰呭鏍?2-宸插鏍?3-宸插彇娑?4-宸插畬鎴?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `audit_status` TINYINT DEFAULT NULL COMMENT '瀹℃牳鐘舵€侊細0-鏈鏍?1-宸插鏍?2-瀹℃牳椹冲洖',
    `audit_time` DATETIME DEFAULT NULL COMMENT '瀹℃牳鏃堕棿',
    `audit_by` BIGINT DEFAULT NULL COMMENT '瀹℃牳浜篒D',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_supplier_code` (`supplier_code`),
    KEY `idx_order_status` (`order_status`),
    KEY `idx_audit_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閲囪喘璁㈠崟涓昏〃';

CREATE TABLE IF NOT EXISTS `purchase_order_item` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `order_id` BIGINT NOT NULL COMMENT '璁㈠崟涓昏〃ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '璁㈠崟缂栧彿',
    `item_no` INT DEFAULT NULL COMMENT '琛屽彿',
    `goods_id` BIGINT DEFAULT NULL COMMENT '鍟嗗搧ID',
    `goods_code` VARCHAR(64) DEFAULT NULL COMMENT '鍟嗗搧缂栫爜',
    `sku_code` VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
    `barcode` VARCHAR(64) DEFAULT NULL COMMENT '条码',
    `goods_name` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧鍚嶇О',
    `goods_spec` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧瑙勬牸鍨嬪彿',
    `unit_code` VARCHAR(32) DEFAULT NULL COMMENT '璁￠噺鍗曚綅缂栫爜',
    `goods_unit` VARCHAR(32) DEFAULT NULL COMMENT '商品单位名称',
    `conversion_rate` DECIMAL(18,4) DEFAULT 1.0000 COMMENT '销售单位到库存基础单位的换算率',
    `quantity` DECIMAL(18,4) NOT NULL COMMENT '閲囪喘鏁伴噺',
    `unit_price` DECIMAL(18,4) NOT NULL COMMENT '鍗曚环锛堜笉鍚◣锛?,
    `amount` DECIMAL(18,4) DEFAULT NULL COMMENT '閲戦锛堜笉鍚◣锛?,
    `tax_rate` DECIMAL(8,4) DEFAULT NULL COMMENT '绋庣巼',
    `is_tax_inclusive` TINYINT DEFAULT 0 COMMENT '标价是否含税(0:否 1:是)',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `discount_rate` DECIMAL(8,4) DEFAULT NULL COMMENT '鎶樻墸鐜?,
    `discount_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '鎶樻墸閲戦',
    `net_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '鍑€閲戦锛堝惈绋庯級',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_goods_code` (`goods_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閲囪喘璁㈠崟鏄庣粏';

CREATE TABLE IF NOT EXISTS `purchase_order_ext` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `order_id` BIGINT NOT NULL COMMENT '璁㈠崟涓昏〃ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '璁㈠崟缂栧彿',
    `ext_key` VARCHAR(128) NOT NULL COMMENT '鎵╁睍瀛楁閿?,
    `ext_value` TEXT DEFAULT NULL COMMENT '鎵╁睍瀛楁鍊?,
    `ext_desc` VARCHAR(255) DEFAULT NULL COMMENT '鎵╁睍瀛楁鎻忚堪',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_ext_key` (`ext_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閲囪喘璁㈠崟鎵╁睍';

CREATE TABLE IF NOT EXISTS `purchase_in_main` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `in_no` VARCHAR(64) NOT NULL COMMENT '鍏ュ簱鍗曠紪鍙?,
    `doc_name` VARCHAR(200) NOT NULL COMMENT '鍗曟嵁鍚嶇О锛堝繀濉紝榛樿锛氬崟鎹被鍨�+褰撳ぉ鏃ユ湡锛�',
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈閲囪喘璁㈠崟缂栧彿',
    `supplier_id` BIGINT DEFAULT NULL COMMENT '渚涘簲鍟咺D',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '渚涘簲鍟嗙紪鐮?,
    `supplier_name` VARCHAR(255) DEFAULT NULL COMMENT '渚涘簲鍟嗗悕绉?,
    `in_date` VARCHAR(20) DEFAULT NULL COMMENT '鍏ュ簱鏃ユ湡',
    `warehouse_code` VARCHAR(64) DEFAULT NULL COMMENT '浠撳簱缂栫爜',
    `warehouse_name` VARCHAR(255) DEFAULT NULL COMMENT '浠撳簱鍚嶇О',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '鍏ュ簱鎬婚噾棰濓紙涓嶅惈绋庯級',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `pay_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '瀹為檯浠樻閲戦',
    `in_status` TINYINT DEFAULT NULL COMMENT '鍏ュ簱鐘舵€侊細1-寰呭鏍?2-宸插鏍?3-宸插彇娑?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `audit_status` TINYINT DEFAULT NULL COMMENT '瀹℃牳鐘舵€侊細0-鏈鏍?1-宸插鏍?2-瀹℃牳椹冲洖',
    `audit_time` DATETIME DEFAULT NULL COMMENT '瀹℃牳鏃堕棿',
    `audit_by` BIGINT DEFAULT NULL COMMENT '瀹℃牳浜篒D',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_in_no` (`in_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_supplier_code` (`supplier_code`),
    KEY `idx_warehouse_code` (`warehouse_code`),
    KEY `idx_in_status` (`in_status`),
    KEY `idx_audit_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閲囪喘鍏ュ簱涓昏〃';

CREATE TABLE IF NOT EXISTS `purchase_in_item` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `in_id` BIGINT NOT NULL COMMENT '鍏ュ簱鍗曚富琛↖D',
    `in_no` VARCHAR(64) NOT NULL COMMENT '鍏ュ簱鍗曠紪鍙?,
    `order_id` BIGINT DEFAULT NULL COMMENT '鍏宠仈閲囪喘璁㈠崟ID',
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈閲囪喘璁㈠崟缂栧彿',
    `item_no` INT DEFAULT NULL COMMENT '琛屽彿',
    `goods_id` BIGINT DEFAULT NULL COMMENT '鍟嗗搧ID',
    `goods_code` VARCHAR(64) DEFAULT NULL COMMENT '鍟嗗搧缂栫爜',
    `sku_code` VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
    `barcode` VARCHAR(64) DEFAULT NULL COMMENT '条码',
    `goods_name` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧鍚嶇О',
    `goods_spec` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧瑙勬牸鍨嬪彿',
    `unit_code` VARCHAR(32) DEFAULT NULL COMMENT '璁￠噺鍗曚綅缂栫爜',
    `goods_unit` VARCHAR(32) DEFAULT NULL COMMENT '商品单位名称',
    `conversion_rate` DECIMAL(18,4) DEFAULT 1.0000 COMMENT '销售单位到库存基础单位的换算率',
    `order_quantity` DECIMAL(18,4) DEFAULT NULL COMMENT '璁㈠崟鏁伴噺',
    `in_quantity` DECIMAL(18,4) NOT NULL COMMENT '瀹為檯鍏ュ簱鏁伴噺',
    `unit_price` DECIMAL(18,4) NOT NULL COMMENT '鍗曚环锛堜笉鍚◣锛?,
    `amount` DECIMAL(18,4) DEFAULT NULL COMMENT '閲戦锛堜笉鍚◣锛?,
    `tax_rate` DECIMAL(8,4) DEFAULT NULL COMMENT '绋庣巼',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `batch_no` VARCHAR(64) DEFAULT NULL COMMENT '鎵规鍙?,
    `expire_date` VARCHAR(20) DEFAULT NULL COMMENT '鏈夋晥鏈?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    KEY `idx_in_id` (`in_id`),
    KEY `idx_in_no` (`in_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_goods_code` (`goods_code`),
    KEY `idx_batch_no` (`batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閲囪喘鍏ュ簱鏄庣粏';

CREATE TABLE IF NOT EXISTS `purchase_return_main` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `return_no` VARCHAR(64) NOT NULL COMMENT '閫€璐у崟缂栧彿',
    `doc_name` VARCHAR(200) NOT NULL COMMENT '鍗曟嵁鍚嶇О锛堝繀濉紝榛樿锛氬崟鎹被鍨�+褰撳ぉ鏃ユ湡锛�',
    `in_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈鍏ュ簱鍗曠紪鍙?,
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '关联采购订单编号',
    `supplier_id` BIGINT DEFAULT NULL COMMENT '渚涘簲鍟咺D',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '渚涘簲鍟嗙紪鐮?,
    `supplier_name` VARCHAR(255) DEFAULT NULL COMMENT '渚涘簲鍟嗗悕绉?,
    `return_date` VARCHAR(20) DEFAULT NULL COMMENT '閫€璐ф棩鏈?,
    `warehouse_code` VARCHAR(64) DEFAULT NULL COMMENT '浠撳簱缂栫爜',
    `warehouse_name` VARCHAR(255) DEFAULT NULL COMMENT '浠撳簱鍚嶇О',
    `total_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '閫€璐ф€婚噾棰濓紙涓嶅惈绋庯級',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `pay_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '瀹為檯閫€娆鹃噾棰?,
    `return_status` TINYINT DEFAULT NULL COMMENT '閫€璐х姸鎬侊細1-寰呭鏍?2-宸插鏍?3-宸插彇娑?,
    `return_reason` VARCHAR(500) DEFAULT NULL COMMENT '閫€璐у師鍥?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `audit_status` TINYINT DEFAULT NULL COMMENT '瀹℃牳鐘舵€侊細0-鏈鏍?1-宸插鏍?2-瀹℃牳椹冲洖',
    `audit_time` DATETIME DEFAULT NULL COMMENT '瀹℃牳鏃堕棿',
    `audit_by` BIGINT DEFAULT NULL COMMENT '瀹℃牳浜篒D',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_return_no` (`return_no`),
    KEY `idx_in_no` (`in_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_supplier_code` (`supplier_code`),
    KEY `idx_return_status` (`return_status`),
    KEY `idx_audit_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閲囪喘閫€璐т富琛?;

CREATE TABLE IF NOT EXISTS `purchase_return_item` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `return_id` BIGINT NOT NULL COMMENT '閫€璐у崟涓昏〃ID',
    `return_no` VARCHAR(64) NOT NULL COMMENT '閫€璐у崟缂栧彿',
    `in_id` BIGINT DEFAULT NULL COMMENT '鍏宠仈鍏ュ簱鍗旾D',
    `in_no` VARCHAR(64) DEFAULT NULL COMMENT '鍏宠仈鍏ュ簱鍗曠紪鍙?,
    `order_no` VARCHAR(64) DEFAULT NULL COMMENT '关联采购订单编号',
    `item_no` INT DEFAULT NULL COMMENT '琛屽彿',
    `goods_id` BIGINT DEFAULT NULL COMMENT '鍟嗗搧ID',
    `goods_code` VARCHAR(64) DEFAULT NULL COMMENT '鍟嗗搧缂栫爜',
    `sku_code` VARCHAR(64) DEFAULT NULL COMMENT 'SKU编码',
    `sku_name` VARCHAR(255) DEFAULT NULL COMMENT 'SKU名称',
    `barcode` VARCHAR(64) DEFAULT NULL COMMENT '条码',
    `goods_name` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧鍚嶇О',
    `goods_spec` VARCHAR(255) DEFAULT NULL COMMENT '鍟嗗搧瑙勬牸鍨嬪彿',
    `unit_code` VARCHAR(32) DEFAULT NULL COMMENT '璁￠噺鍗曚綅缂栫爜',
    `goods_unit` VARCHAR(32) DEFAULT NULL COMMENT '商品单位名称',
    `conversion_rate` DECIMAL(18,4) DEFAULT 1.0000 COMMENT '销售单位到库存基础单位的换算率',
    `in_quantity` DECIMAL(18,4) DEFAULT NULL COMMENT '鍏ュ簱鏁伴噺',
    `return_quantity` DECIMAL(18,4) NOT NULL COMMENT '閫€璐ф暟閲?,
    `unit_price` DECIMAL(18,4) NOT NULL COMMENT '鍗曚环锛堜笉鍚◣锛?,
    `amount` DECIMAL(18,4) DEFAULT NULL COMMENT '閲戦锛堜笉鍚◣锛?,
    `tax_rate` DECIMAL(8,4) DEFAULT NULL COMMENT '绋庣巼',
    `tax_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '绋庨',
    `batch_no` VARCHAR(64) DEFAULT NULL COMMENT '鎵规鍙?,
    `expire_date` VARCHAR(20) DEFAULT NULL COMMENT '鏈夋晥鏈?,
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    KEY `idx_return_id` (`return_id`),
    KEY `idx_return_no` (`return_no`),
    KEY `idx_in_no` (`in_no`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_goods_code` (`goods_code`),
    KEY `idx_batch_no` (`batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='閲囪喘閫€璐ф槑缁?;

CREATE TABLE IF NOT EXISTS `supplier` (
    `id` BIGINT AUTO_INCREMENT COMMENT '涓婚敭ID',
    `data_uuid` VARCHAR(64) DEFAULT NULL COMMENT '数据唯一标识（雪花算法生成），用于分布式数据同步',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '绉熸埛ID',
    `supplier_code` VARCHAR(64) NOT NULL COMMENT '渚涘簲鍟嗙紪鐮?,
    `supplier_name` VARCHAR(255) NOT NULL COMMENT '渚涘簲鍟嗗叏绉?,
    `short_name` VARCHAR(100) DEFAULT NULL COMMENT '渚涘簲鍟嗙畝绉?,
    `contact_name` VARCHAR(100) DEFAULT NULL COMMENT '鑱旂郴浜哄鍚?,
    `contact_phone` VARCHAR(50) DEFAULT NULL COMMENT '鑱旂郴浜虹數璇?,
    `email` VARCHAR(100) DEFAULT NULL COMMENT '鐢靛瓙閭',
    `address` VARCHAR(500) DEFAULT NULL COMMENT '璇︾粏鍦板潃',
    `province` VARCHAR(100) DEFAULT NULL COMMENT '鐪佷唤',
    `city` VARCHAR(100) DEFAULT NULL COMMENT '鍩庡競',
    `district` VARCHAR(100) DEFAULT NULL COMMENT '鍖哄幙',
    `zip_code` VARCHAR(20) DEFAULT NULL COMMENT '閭斂缂栫爜',
    `tax_no` VARCHAR(50) DEFAULT NULL COMMENT '绋庡姟鐧昏鍙?,
    `bank_name` VARCHAR(100) DEFAULT NULL COMMENT '寮€鎴烽摱琛屽悕绉?,
    `bank_account` VARCHAR(50) DEFAULT NULL COMMENT '閾惰璐﹀彿',
    `supplier_type` VARCHAR(20) DEFAULT NULL COMMENT '渚涘簲鍟嗙被鍨嬶細1-鏅€氫緵搴斿晢 2-鏍稿績渚涘簲鍟?3-鎴樼暐渚涘簲鍟?,
    `industry` VARCHAR(100) DEFAULT NULL COMMENT '鎵€灞炶涓?,
    `credit_level` VARCHAR(10) DEFAULT NULL COMMENT '淇＄敤绛夌骇锛欰/B/C/D',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '澶囨敞',
    `create_by` BIGINT DEFAULT NULL COMMENT '鍒涘缓浜篒D',
    `create_time` DATETIME DEFAULT NULL COMMENT '鍒涘缓鏃堕棿',
    `update_by` BIGINT DEFAULT NULL COMMENT '鏇存柊浜篒D',
    `update_time` DATETIME DEFAULT NULL COMMENT '鏇存柊鏃堕棿',
    `del_flag` TINYINT DEFAULT 0 COMMENT '鍒犻櫎鏍囪锛?-鏈垹闄?1-宸插垹闄?,
    `status` TINYINT DEFAULT 1 COMMENT '鐘舵€侊細1-鍚敤 0-绂佺敤',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_data_uuid` (`data_uuid`),
    UNIQUE KEY `uk_supplier_code` (`supplier_code`),
    KEY `idx_supplier_name` (`supplier_name`),
    KEY `idx_supplier_type` (`supplier_type`),
    KEY `idx_industry` (`industry`),
    KEY `idx_credit_level` (`credit_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='渚涘簲鍟嗚〃';